import nextConfig from "eslint-config-next/core-web-vitals"

const config = [
  {
    // Generated output only. `coverage/` holds istanbul's HTML reporter, which vendors
    // third-party scripts (prettify.js, sorter.js, block-navigation.js) carrying their own
    // eslint-disable headers — linting them produced 6 permanent "unused eslint-disable"
    // warnings in the editor Problems panel for files that are gitignored, untracked, and
    // regenerated by every `pnpm test:coverage`. Every other build directory was already
    // listed here; this one was missed.
    ignores: [
      ".next/**",
      ".next-e2e/**",
      ".next-e2e-manual/**",
      "playwright-report/**",
      "test-results/**",
      ".tmp/**",
      "coverage/**",
    ],
  },
  ...nextConfig,
  {
    rules: {
      "react-hooks/set-state-in-effect": "off",
    },
  },
]

export default config
