import { readFileSync } from "node:fs"
import { resolve } from "node:path"
import { describe, expect, it } from "vitest"

/**
 * The pnpm security overrides must still be there.
 *
 * REPORTED BY THE QA SCANNER, 2026-09-02: `pnpm@latest` now resolves to v11, which hard-fails on
 * routine build-script warnings and, on install, **silently rewrote pnpm-lock.yaml and
 * pnpm-workspace.yaml and stripped this repo's `pnpm.overrides` block**. The scanner noticed and
 * reverted it before committing. Nothing in the repo would have noticed if it had not.
 *
 * That block is not preference. Every entry is a pinned floor over a known-vulnerable transitive
 * dependency, and losing one is a supply-chain regression that shows up as nothing at all: the
 * build passes, the tests pass, and the vulnerable version is back in the tree. It is exactly the
 * house failure mode -- no error, a confident wrong answer -- applied to dependencies instead of
 * money.
 *
 * TWO GUARDS, because they fail differently:
 *
 *   packageManager + engines   stop pnpm 11 running here at all. A version pin is the fix; this
 *                              test is the net for when someone bumps it without thinking.
 *   the override list          catches the damage if it happens anyway, through corepack being
 *                              disabled, a --force install, or a tool that ignores both fields.
 *
 * CI already pins `pnpm/action-setup@v4` to version 10, so CI was never at risk. The exposure was
 * a human or an agent running `pnpm install` locally and committing the result -- which is how the
 * lockfile gets rewritten in the first place.
 */
const pkg = JSON.parse(readFileSync(resolve(__dirname, "../package.json"), "utf8"))

/** Each of these was added deliberately. Removing one needs a reason in the commit message. */
const REQUIRED_OVERRIDES = [
  "glob",
  "minimatch@<3.1.4",
  "minimatch@>=9.0.0 <9.0.7",
  "rollup@<4.59.0",
  "esbuild@<=0.24.2",
  "ajv@<6.14.0",
  "dompurify@<=3.3.1",
]

describe("the package manager is pinned to a major that does not eat the lockfile", () => {
  it("declares packageManager, so corepack and pnpm both refuse the wrong version", () => {
    expect(pkg.packageManager).toMatch(/^pnpm@10\./)
  })

  it("and states the range in engines, for the tools that read that instead", () => {
    expect(pkg.engines?.pnpm).toBe(">=10 <11")
  })

  it("is the ONLY place a pnpm version is stated", () => {
    /**
     * This test asserted the opposite three days ago, and that assertion is what broke CI.
     *
     * It required `version: 10` in ci.yml *as well as* the packageManager pin, on the reasoning
     * that two pins are safer than one. pnpm/action-setup@v4 disagrees: specifying both is a hard
     * error -- "Multiple versions of pnpm specified" -- and it fails at Setup pnpm in under fifteen
     * seconds, before lint, typecheck, tests or build run at all.
     *
     * So from 2026-09-02, the day the pin landed, every push to main went red for a reason that
     * had nothing to do with the code, and the local pre-push gate kept passing, so nobody looked.
     * Belt and braces is not free when the belt and the braces are checked against each other.
     *
     * One source of truth, and it is package.json: exact (10.28.2, not 10), read by
     * action-setup in CI, and the field that governs local installs -- which is the whole point,
     * since pnpm 11 strips the overrides above on install.
     */
    const ci = readFileSync(resolve(__dirname, "../.github/workflows/ci.yml"), "utf8")
    expect((ci.match(/pnpm\/action-setup@v4/g) ?? []).length).toBeGreaterThan(0)
    // Any pnpm version in the workflow now conflicts with packageManager, whatever it says.
    const setupBlocks = ci.split("pnpm/action-setup@v4").slice(1)
    for (const block of setupBlocks) {
      expect(block.slice(0, 200), "a version beside packageManager is a hard error").not.toMatch(/^\s*with:[\s\S]*version:/)
    }
  })
})

describe("the security overrides survive an install", () => {
  it("still carries every pinned floor", () => {
    const overrides = pkg.pnpm?.overrides ?? {}
    const missing = REQUIRED_OVERRIDES.filter((key) => !(key in overrides))
    expect(
      missing,
      "a pnpm install stripped these — the vulnerable transitive versions are back in the tree",
    ).toEqual([])
  })

  it("has no empty or placeholder pins", () => {
    // A key that survives with an empty value satisfies "is it there" and pins nothing.
    for (const [key, value] of Object.entries(pkg.pnpm?.overrides ?? {})) {
      expect(String(value ?? "").trim(), `override ${key} has no version`).not.toBe("")
    }
  })

  it("the lockfile has not been rewritten by a different major", () => {
    // pnpm 11 writes a newer lockfileVersion. If this ever trips, the lockfile was regenerated by
    // the wrong pnpm and the overrides above should be checked by hand before trusting them.
    const lock = readFileSync(resolve(__dirname, "../pnpm-lock.yaml"), "utf8")
    const version = lock.match(/^lockfileVersion:\s*'?([\d.]+)'?/m)?.[1]
    expect(version, "unexpected lockfileVersion — regenerated by a different pnpm major?").toBe("9.0")
  })
})
