import { readFileSync } from "node:fs"
import { resolve } from "node:path"
import { describe, expect, it } from "vitest"

/**
 * The pnpm security overrides must still be there.
 *
 * REPORTED BY THE QA SCANNER, 2026-09-02: `pnpm@latest` now resolves to v11, which hard-fails on
 * routine build-script warnings and, on install, **silently rewrote pnpm-lock.yaml and
 * pnpm-workspace.yaml and stripped this repo's `pnpm.overrides` block**. The scanner noticed and
 * reverted it before committing. Nothing in the repo would have noticed if it had not.
 *
 * That block is not preference. Every entry is a pinned floor over a known-vulnerable transitive
 * dependency, and losing one is a supply-chain regression that shows up as nothing at all: the
 * build passes, the tests pass, and the vulnerable version is back in the tree. It is exactly the
 * house failure mode -- no error, a confident wrong answer -- applied to dependencies instead of
 * money.
 *
 * TWO GUARDS, because they fail differently:
 *
 *   packageManager + engines   stop pnpm 11 running here at all. A version pin is the fix; this
 *                              test is the net for when someone bumps it without thinking.
 *   the override list          catches the damage if it happens anyway, through corepack being
 *                              disabled, a --force install, or a tool that ignores both fields.
 *
 * CI already pins `pnpm/action-setup@v4` to version 10, so CI was never at risk. The exposure was
 * a human or an agent running `pnpm install` locally and committing the result -- which is how the
 * lockfile gets rewritten in the first place.
 */
const pkg = JSON.parse(readFileSync(resolve(__dirname, "../package.json"), "utf8"))

/** Each of these was added deliberately. Removing one needs a reason in the commit message. */
const REQUIRED_OVERRIDES = [
  "glob",
  "minimatch@<3.1.4",
  "minimatch@>=9.0.0 <9.0.7",
  "rollup@<4.59.0",
  "esbuild@<=0.24.2",
  "ajv@<6.14.0",
  "dompurify@<=3.3.1",
]

describe("the package manager is pinned to a major that does not eat the lockfile", () => {
  it("declares packageManager, so corepack and pnpm both refuse the wrong version", () => {
    expect(pkg.packageManager).toMatch(/^pnpm@10\./)
  })

  it("and states the range in engines, for the tools that read that instead", () => {
    expect(pkg.engines?.pnpm).toBe(">=10 <11")
  })

  it("stays in step with CI, which pins the same major", () => {
    const ci = readFileSync(resolve(__dirname, "../.github/workflows/ci.yml"), "utf8")
    // Two setup steps, both pinned. A pin on one and not the other is how they drift.
    expect((ci.match(/pnpm\/action-setup@v4/g) ?? []).length).toBeGreaterThan(0)
    expect(ci).toMatch(/version:\s*10/)
    expect(ci).not.toMatch(/version:\s*(11|latest)/)
  })
})

describe("the security overrides survive an install", () => {
  it("still carries every pinned floor", () => {
    const overrides = pkg.pnpm?.overrides ?? {}
    const missing = REQUIRED_OVERRIDES.filter((key) => !(key in overrides))
    expect(
      missing,
      "a pnpm install stripped these — the vulnerable transitive versions are back in the tree",
    ).toEqual([])
  })

  it("has no empty or placeholder pins", () => {
    // A key that survives with an empty value satisfies "is it there" and pins nothing.
    for (const [key, value] of Object.entries(pkg.pnpm?.overrides ?? {})) {
      expect(String(value ?? "").trim(), `override ${key} has no version`).not.toBe("")
    }
  })

  it("the lockfile has not been rewritten by a different major", () => {
    // pnpm 11 writes a newer lockfileVersion. If this ever trips, the lockfile was regenerated by
    // the wrong pnpm and the overrides above should be checked by hand before trusting them.
    const lock = readFileSync(resolve(__dirname, "../pnpm-lock.yaml"), "utf8")
    const version = lock.match(/^lockfileVersion:\s*'?([\d.]+)'?/m)?.[1]
    expect(version, "unexpected lockfileVersion — regenerated by a different pnpm major?").toBe("9.0")
  })
})
