import { describe, expect, it } from "vitest"

import { computeWorkerPay, type PeriodInput } from "../lib/payroll-period"
import type { LedgerEntry, PayRule } from "../lib/pay-rules"
// Plain .mjs, shared with the dev seeder so the report and the database cannot disagree.
// @ts-ignore -- no type declarations for a dev-only scenario module
import { WEEKS, WORKERS, ESTATE_RULE, workedDaysFor } from "../scripts/dev/payroll-month-scenarios.mjs"

/**
 * A whole month of an estate, run through the real payroll code.
 *
 * Not a fixture of expected numbers — the report is GENERATED by the same functions the API calls,
 * so if the arithmetic changes the printed sheet changes with it. Print it with:
 *
 *   pnpm vitest run tests/payroll-month-report.test.ts --reporter=verbose
 *
 * The assertions at the bottom pin the handful of figures that would be silently wrong rather than
 * obviously wrong, which is the only kind this product actually produces.
 */

const money = (n: number) => `₹${n.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
const pad = (s: string | number, n: number) => String(s).padEnd(n)
const rpad = (s: string | number, n: number) => String(s).padStart(n)

type Row = {
  key: string
  week: string
  days: number
  gross: number
  overtime: number
  retention: number
  advance: number
  shortfall: number
  allowance: number
  deduction: number
  net: number
  held: number
  owed: number
}

function buildMonth(): { rows: Row[]; byWorker: Map<string, Row[]> } {
  const rules: PayRule[] = [ESTATE_RULE as PayRule]
  for (const w of WORKERS as any[]) {
    if (w.rule) {
      rules.push({
        workerId: w.key,
        effectiveFrom: w.rule.effectiveFrom,
        retentionMode: null,
        retentionValue: null,
        overtimeMode: null,
        overtimeValue: null,
        fullDayHours: null,
        pfPercent: null,
      })
    }
  }

  const ledger: (LedgerEntry & { workerId: string })[] = []
  const overtimeDays: { workerId: string; workDate: string; hours: number }[] = []
  const workedDays: { workerId: string; workDate: string; dayFraction: number; rate: number }[] = []

  for (const w of WORKERS as any[]) {
    for (const d of workedDaysFor(w)) workedDays.push({ workerId: w.key, ...d })
    for (const o of w.overtime ?? []) overtimeDays.push({ workerId: w.key, workDate: o.date, hours: o.hours })
    for (const [i, e] of (w.ledger ?? []).entries()) {
      ledger.push({
        workerId: w.key,
        id: `${w.key}-${i}`,
        entryType: e.type,
        entryDate: e.date,
        amount: e.amount,
        recoverOverPeriods: e.periods ?? 1,
        recoverFrom: null,
      })
    }
  }

  const rows: Row[] = []
  const byWorker = new Map<string, Row[]>()

  for (const week of WEEKS as any[]) {
    for (const w of WORKERS as any[]) {
      const daysThisWeek = workedDays.filter(
        (d) => d.workerId === w.key && d.workDate >= week.start && d.workDate <= week.end,
      )
      if (daysThisWeek.length === 0 && !(w.ledger ?? []).some((e: any) => e.date >= week.start && e.date <= week.end)) {
        continue // absent that week, and nothing owed — not a zero line, simply not on the sheet
      }

      const gross = daysThisWeek.reduce((s, d) => s + d.rate * d.dayFraction, 0)

      // Allowances and one-off deductions are period-scoped, exactly as payroll-summary scopes them.
      const inWeek = (e: any) => e.entryDate >= week.start && e.entryDate <= week.end
      const allowance = ledger
        .filter((e) => e.workerId === w.key && e.entryType === "adjustment" && inWeek(e))
        .reduce((s, e) => s + e.amount, 0)
      const deduction = ledger
        .filter((e) => e.workerId === w.key && e.entryType === "deduction" && inWeek(e))
        .reduce((s, e) => s + e.amount, 0)

      const input: PeriodInput = {
        rules,
        workedDays: daysThisWeek,
        overtimeDays: overtimeDays.filter(
          (o) => o.workerId === w.key && o.workDate >= week.start && o.workDate <= week.end,
        ),
        ledger: ledger.filter((e) => e.workerId === w.key),
        periodStart: week.start,
      }
      const pay = computeWorkerPay(input, w.key, gross)

      const row: Row = {
        key: w.key,
        week: week.label,
        days: daysThisWeek.reduce((s, d) => s + d.dayFraction, 0),
        gross,
        overtime: pay.overtime,
        retention: pay.retention,
        advance: pay.advanceRecovered,
        shortfall: pay.shortfall,
        allowance,
        deduction,
        net: Math.max(0, gross + pay.overtime + allowance - deduction - pay.retention - pay.advanceRecovered),
        held: pay.heldAfter,
        owed: pay.owedAfter,
      }
      rows.push(row)
      if (!byWorker.has(w.key)) byWorker.set(w.key, [])
      byWorker.get(w.key)!.push(row)
    }
  }

  return { rows, byWorker }
}

const { rows, byWorker } = buildMonth()

describe("August 2026 at Medappa — one month, ten people, every situation", () => {
  it("prints the wage sheet", () => {
    const W = [22, 8, 6, 12, 10, 11, 11, 10, 9, 12]
    for (const week of WEEKS as any[]) {
      console.log(`\n\n══ ${week.label} ${"═".repeat(60)}`)
      console.log(
        pad("Worker", W[0]) + rpad("Days", W[2]) + rpad("Gross", W[3]) + rpad("Overtime", W[4]) +
          rpad("Allowance", W[5]) + rpad("Retention", W[6]) + rpad("Advance", W[7]) + rpad("Other", W[8]) +
          rpad("NET", W[9]),
      )
      console.log("─".repeat(101))
      const weekRows = rows.filter((r) => r.week === week.label)
      for (const r of weekRows) {
        console.log(
          pad(r.key, W[0]) +
            rpad(r.days, W[2]) +
            rpad(money(r.gross), W[3]) +
            rpad(r.overtime ? money(r.overtime) : "—", W[4]) +
            rpad(r.allowance ? money(r.allowance) : "—", W[5]) +
            rpad(r.retention ? `-${money(r.retention)}` : "—", W[6]) +
            rpad(r.advance ? `-${money(r.advance)}` : "—", W[7]) +
            rpad(r.deduction ? `-${money(r.deduction)}` : "—", W[8]) +
            rpad(money(r.net), W[9]) +
            (r.shortfall ? `   ⚠ ${money(r.shortfall)} unrecovered` : ""),
        )
      }
      const t = weekRows.reduce(
        (a, r) => ({
          gross: a.gross + r.gross, ot: a.ot + r.overtime, allow: a.allow + r.allowance,
          ret: a.ret + r.retention, adv: a.adv + r.advance, ded: a.ded + r.deduction, net: a.net + r.net,
        }),
        { gross: 0, ot: 0, allow: 0, ret: 0, adv: 0, ded: 0, net: 0 },
      )
      console.log("─".repeat(101))
      console.log(
        pad(`${weekRows.length} on the sheet`, W[0] + W[2]) +
          rpad(money(t.gross), W[3]) + rpad(t.ot ? money(t.ot) : "—", W[4]) +
          rpad(t.allow ? money(t.allow) : "—", W[5]) + rpad(`-${money(t.ret)}`, W[6]) +
          rpad(t.adv ? `-${money(t.adv)}` : "—", W[7]) + rpad(t.ded ? `-${money(t.ded)}` : "—", W[8]) +
          rpad(money(t.net), W[9]),
      )
    }

    console.log(`\n\n══ WHERE EACH PERSON STANDS AFTER THE MONTH ${"═".repeat(38)}`)
    console.log(pad("Worker", 22) + rpad("Month net", 14) + rpad("Held", 12) + rpad("Owes", 12) + "  Situation")
    console.log("─".repeat(120))
    for (const w of WORKERS as any[]) {
      const mine = byWorker.get(w.key) ?? []
      if (mine.length === 0) continue
      const net = mine.reduce((s, r) => s + r.net, 0)
      const last = mine[mine.length - 1]
      console.log(
        pad(w.key, 22) + rpad(money(net), 14) + rpad(money(last.held), 12) + rpad(money(last.owed), 12) +
          "  " + w.story,
      )
    }
    console.log("")
    expect(rows.length).toBeGreaterThan(0)
  })
})

describe("the figures that would be silently wrong rather than obviously wrong", () => {
  const w = (key: string) => byWorker.get(key)!
  const week = (key: string, i: number) => w(key)[i]

  it("the steady worker: six days at Rs 600, 20% held, nothing else", () => {
    const r = week("steady", 0)
    expect(r.gross).toBe(3600)
    expect(r.retention).toBe(720)
    expect(r.net).toBe(2880)
  })

  it("half days hold half — 4.5 days is Rs 2,700 and Rs 540, not 6 days' worth", () => {
    const r = week("half_days", 0)
    expect(r.days).toBe(5)
    expect(r.gross).toBe(3000)
    expect(r.retention).toBe(600)
  })

  it("the big advance recovers NOTHING from the week before it was given", () => {
    // Taken on 12 Aug, which is W2. W1 ended on the 8th and was already paid. This is the bug the
    // month simulation found on its first run: a global period ordinal recovered from week one.
    const wk = w("big_advance")
    expect(wk[0].week).toContain("W1")
    expect(wk[0].advance).toBe(0)
  })

  it("and then takes Rs 2,000 a week, never Rs 20,000", () => {
    const wk = w("big_advance")
    for (const r of wk.slice(1)) expect(r.advance).toBe(2000)
    expect(wk[3].owed).toBe(14000) // 20,000 less the three instalments taken by the end of W4
  })

  it("the thin week caps recovery at the wage and states the rest", () => {
    // Advance taken 10 Aug -- inside W2, which is also the week they worked only two days.
    const r = week("thin_week", 1)
    expect(r.week).toContain("W2")
    expect(r.gross).toBe(1200)
    expect(r.retention).toBe(240)
    expect(r.advance).toBe(960)
    expect(r.net).toBe(0)
    expect(r.shortfall).toBe(9040)
  })

  it("and the following week recovers nothing more, because a one-run advance had its run", () => {
    // The debt stays; the schedule does not extend itself to chase it. That is the estate's
    // decision, not something payroll does quietly on the next wage.
    expect(week("thin_week", 2).advance).toBe(0)
    expect(week("thin_week", 2).net).toBe(2880)
  })

  it("an early repayment shortens the recovery instead of being collected twice", () => {
    /**
     * Rs 8,000 taken 5 Aug over four runs; Rs 3,000 handed back in cash on the 20th.
     *
     * ⚠ THIS TEST USED TO ASSERT THE BUG, and its own comment said so out loud: "8,000 less 3,000
     * repaid less four instalments, FLOORED AT ZERO". Four instalments is Rs 8,000 from wages, and
     * with Rs 3,000 already returned that is Rs 11,000 collected against Rs 8,000 lent. The floor
     * was not a safety net, it was the thing hiding the overcharge — owed read a tidy Rs 0 the
     * whole way down.
     *
     * Written from what the code did rather than from what the estate owes, which is how a test
     * ends up defending a defect. Greptile raised the underlying fault on 2026-09-11.
     *
     * Now the schedule is bounded by the debt: W1 and W2 take their full Rs 2,000, W3 takes the
     * Rs 1,000 that is left, W4 takes nothing. Rs 5,000 from wages plus Rs 3,000 in cash is
     * exactly Rs 8,000.
     */
    const wk = w("repaid_early")
    expect(wk.map((r: any) => r.advance)).toEqual([2000, 2000, 1000, 0])
    expect(wk.reduce((sum: number, r: any) => sum + r.advance, 0)).toBe(5000)
    expect(wk[3].owed).toBe(0) // owed nothing, and nothing over-collected to get there
  })

  it("the exempt worker is held nothing, on a higher rate, all month", () => {
    for (const r of w("exempt")) {
      expect(r.retention).toBe(0)
      expect(r.gross).toBe(4500) // 6 x 750
    }
  })

  it("overtime pays Rs 90 an hour and does not increase retention", () => {
    const r = week("overtime", 0) // 3 hours on 6 Aug
    expect(r.overtime).toBe(270)
    expect(r.retention).toBe(720) // on the days, not the extra hours
    expect(r.net).toBe(3150)
  })

  it("an allowance is added and a fine subtracted, neither touching retention", () => {
    const wk = w("allowance_and_fine")
    expect(wk[1].allowance).toBe(2000)
    expect(wk[1].net).toBe(3600 + 2000 - 720)
    expect(wk[2].deduction).toBe(500)
    expect(wk[2].net).toBe(3600 - 500 - 720)
  })

  it("someone who joined late is absent from the earlier sheets, not paid zero on them", () => {
    // A zero line reads as "worked and earned nothing", which is a different and alarming thing.
    expect(w("joined_late").length).toBe(2)
    expect(w("joined_late")[0].week).toContain("W3")
  })

  it("a mid-month rate rise changes retention with it, with no rule edited", () => {
    const wk = w("rate_rise")
    expect(wk[0].gross).toBe(3600) // Rs 600 days
    expect(wk[0].retention).toBe(720)
    expect(wk[2].gross).toBe(4200) // Rs 700 days from the 16th
    expect(wk[2].retention).toBe(840)
  })

  it("nobody is ever paid a negative wage", () => {
    for (const r of rows) expect(r.net).toBeGreaterThanOrEqual(0)
  })

  it("the held figure is per-run, NOT a running balance — and that is the derive-or-write cost", () => {
    /**
     * heldAfter sums retention_accrual ROWS plus this run's retention, and retention is derived
     * rather than written — so there are no rows and it reports one week, not four.
     *
     * Asserted as it actually behaves rather than as it ought to, because a test that quietly
     * expects the right answer from the wrong mechanism hides the gap. The month total is the sum
     * of the weekly figures; the Workers panel derives its own balance from the full ledger.
     *
     * This is the concrete price of deriving retention instead of writing it
     * (docs/PAYROLL-NEXT-STEPS.md step 1). Whoever closes that decision deletes this test.
     */
    for (const [key, mine] of byWorker) {
      if (key === "exempt") continue
      const lastWeek = mine[mine.length - 1]
      expect(lastWeek.held).toBe(lastWeek.retention)
      const monthTotal = mine.reduce((s, r) => s + r.retention, 0)
      expect(monthTotal).toBeGreaterThanOrEqual(lastWeek.held)
    }
  })
})
