export default function BillingPolicyPage() {
  return (
    <div className="mx-auto w-full max-w-3xl space-y-6 px-6 py-12">
      <div className="space-y-2">
        <p className="text-xs uppercase tracking-[0.3em] text-muted-foreground">Legal</p>
        <h1 className="text-3xl font-semibold text-foreground">Billing, Cancellation & Refund Policy</h1>
        <p className="text-sm text-muted-foreground">Effective: 2026-04-01</p>
      </div>

      <section className="space-y-3 text-sm text-muted-foreground">
        <p>
          This policy applies to FarmFlow software subscriptions. It does not apply to GST invoices or commercial
          documents created by customers inside the product.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold text-foreground">Trials And Renewals</h2>
        <p className="text-sm text-muted-foreground">
          Eligible new workspaces may receive a 30-day trial. Where a recurring payment mandate is required, the
          customer must complete the authorisation flow before automatic renewals can begin. Paid cycles renew according
          to the plan selected at checkout unless cancelled before the next billing cycle.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold text-foreground">Cancellation</h2>
        <p className="text-sm text-muted-foreground">
          Cancellation stops future renewals. Access already granted for the current billed cycle generally remains
          available until the end of that cycle unless the account is suspended for misuse, fraud, or non-payment.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold text-foreground">Refunds</h2>
        <p className="text-sm text-muted-foreground">
          Fees for an already-started billing cycle are generally non-refundable except in cases of duplicate charge,
          proven billing error, failed provisioning that is not cured in reasonable time, or where refund is required by
          law.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold text-foreground">Taxes And Billing Records</h2>
        <p className="text-sm text-muted-foreground">
          Applicable taxes, including GST where required, are handled as part of the FarmFlow software subscription
          relationship and are separate from operational invoices generated by customers in the app.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold text-foreground">Support And Disputes</h2>
        <p className="text-sm text-muted-foreground">
          For billing issues, duplicate charges, or cancellation questions, contact support through the FarmFlow contact
          channel. We retain billing events, policy versions, and service access logs to investigate subscription
          disputes.
        </p>
      </section>
    </div>
  )
}
