export type AccountActivitySuggestion = {
  code: string
  reference: string
}

// Snapshot derived from the live HoneyFarm and Seshagiri activity lists so
// newer tenants can start from a proven structure instead of a blank screen.
export const ACCOUNT_ACTIVITY_SUGGESTIONS: AccountActivitySuggestion[] = [
  { code: "101", reference: "Salaries And Allowances" },
  { code: "101A", reference: "Writer Wage & Benefits" },
  { code: "101B", reference: "Supervisor" },
  { code: "102", reference: "Provident Fund, Insurance" },
  { code: "103", reference: "Bonus Staff And Labour" },
  { code: "104", reference: "Gratuity" },
  { code: "105", reference: "Bungalow Servants" },
  { code: "106", reference: "Leave With Wages" },
  { code: "107", reference: "Sickness Benifit" },
  { code: "108", reference: "Medical Exp Staff, Labour" },
  { code: "109", reference: "Labour Welfare" },
  { code: "110", reference: "Postage, Stationary" },
  { code: "111", reference: "Watchman Estate, Drying Yard" },
  { code: "112", reference: "Vehicle Running & Maint" },
  { code: "113", reference: "Electricity" },
  { code: "115", reference: "Machinary Maintenance" },
  { code: "116", reference: "Land Tax" },
  { code: "117", reference: "Maint Build, Roads, Yard" },
  { code: "118", reference: "Weather Protectives" },
  { code: "119", reference: "Cattle Expenses" },
  { code: "120", reference: "Water Supply" },
  { code: "121", reference: "Telephone Bill" },
  { code: "122", reference: "Miscellaneous" },
  { code: "123", reference: "Tools And Implements" },
  { code: "131", reference: "Arabica Weeding, Trenching" },
  { code: "132", reference: "Arabica Pruning, Handling" },
  { code: "133", reference: "Arabica Borer Tracing" },
  { code: "134", reference: "Arabica Shade Work" },
  { code: "135", reference: "Arabica, Cost Lime, Manure" },
  { code: "136", reference: "Arabica Lime, Manuring" },
  { code: "137", reference: "Arabica Spraying" },
  { code: "138", reference: "Arabica Fence" },
  { code: "139", reference: "Arabica Supplies, Upkeep" },
  { code: "140", reference: "Arabica Harvesting" },
  { code: "141", reference: "Arabica Processing & Drying" },
  { code: "143", reference: "Arabica Irrigation" },
  { code: "144", reference: "Arabica Harvesting incentive" },
  { code: "150", reference: "Drip line Maintenance" },
  { code: "151", reference: "Robusta Weeding" },
  { code: "152", reference: "Robusta Pruning, Handling" },
  { code: "153", reference: "Pest Control, Berry Borer" },
  { code: "154", reference: "Robusta Shade Temp, Perm." },
  { code: "155", reference: "Robusta, Cost Lime, Manure" },
  { code: "156", reference: "Robusta Liming, Manuring" },
  { code: "157", reference: "Robusta Spray" },
  { code: "158", reference: "Robusta Fence Maint" },
  { code: "159", reference: "Supplies Planting, Upkeep" },
  { code: "160", reference: "Robust Harvesting" },
  { code: "161", reference: "Robusta Processing & Drying" },
  { code: "162", reference: "Robusta Curing" },
  { code: "163", reference: "Robusta Irrigation" },
  { code: "164", reference: "Robusta Harvesting incentive" },
  { code: "181", reference: "Pepper Planting, Upkeep" },
  { code: "182", reference: "Pepper Manuring" },
  { code: "183", reference: "Pepper Pest & Disease Cont." },
  { code: "184", reference: "Pepper Havest, Process, Pack" },
  { code: "185", reference: "Compost Preperation" },
  { code: "191", reference: "Paddy Cultivation" },
  { code: "200", reference: "arecanut composting" },
  { code: "201", reference: "Arecanut" },
  { code: "202", reference: "Orange" },
  { code: "204", reference: "Ginger" },
  { code: "206", reference: "Other Crops" },
  { code: "210", reference: "Nursery" },
  { code: "211", reference: "New Clearing" },
  { code: "212", reference: "Planting Temporary Shade" },
  { code: "213", reference: "Lining" },
  { code: "214", reference: "Pitting" },
  { code: "215", reference: "New Planting, Clearing" },
  { code: "216", reference: "Mulching & Staking" },
  { code: "217", reference: "Cover Digging" },
  { code: "218", reference: "Sheltering" },
  { code: "219", reference: "Lime" },
  { code: "220", reference: "Weeding - (New Clearing)" },
  { code: "221", reference: "Pests & Diseses" },
  { code: "222", reference: "Fence (New Clearing)" },
  { code: "232", reference: "Lent" },
  { code: "233", reference: "Capital Account" },
  { code: "245", reference: "Organic Compost Manure" },
  { code: "555", reference: "Solar Fence" },
]

const normalizeCode = (value: unknown) => String(value || "").trim().toUpperCase()

export const buildMissingAccountActivitySuggestions = (existingCodes: Array<unknown>) => {
  const existing = new Set(existingCodes.map((value) => normalizeCode(value)).filter(Boolean))
  return ACCOUNT_ACTIVITY_SUGGESTIONS.filter((suggestion) => !existing.has(suggestion.code))
}
