#!/usr/bin/env node
/**
 * Regenerates the seam map in docs/TAB-SEAMS.md.
 *
 * Joins three things: which components make up each tab, which /api routes those components fetch,
 * and which tables those routes query. Table names are validated against the live dev schema, so a
 * SQL keyword or CTE alias cannot masquerade as a table -- without that check the first version of
 * this reported "one", "ever" and "an" as shared tables.
 *
 * The output narrows where to look. It is NOT evidence: a tab appears beside a table because some
 * route it calls mentions that table, which is not the same as the tab surfacing a number derived
 * from it. Confirm the read path before writing a finding.
 */
import { readFileSync, writeFileSync } from "node:fs"
import { execSync } from "node:child_process"
import { neon } from "@neondatabase/serverless"

for (const line of readFileSync(".env.local", "utf8").split("\n")) {
  const m = line.match(/^([A-Z0-9_]+)=(.*)$/)
  if (m) process.env[m[1]] ??= m[2].trim().replace(/^["']|["']$/g, "")
}

const sql = neon(process.env.DATABASE_URL_DEV)
const real = new Set(
  (await sql`SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'`).map(
    (r) => r.table_name,
  ),
)

/** Everything touches these; listing them says nothing. */
const UBIQUITOUS = ["tenants", "locations", "users", "audit_log", "tenant_modules"]

const ls = (pattern) =>
  execSync(`git ls-files '${pattern}'`, { encoding: "utf8" }).split("\n").filter(Boolean)

const routeTables = new Map()
for (const file of ls("app/api/**/route.ts")) {
  const src = readFileSync(file, "utf8")
  const tables = new Set()
  for (const m of src.matchAll(/\b(?:FROM|JOIN|INTO|UPDATE)\s+([a-z_][a-z0-9_]*)/gi)) {
    const t = m[1].toLowerCase()
    if (real.has(t)) tables.add(t)
  }
  routeTables.set("/" + file.replace(/^app\//, "").replace(/\/route\.ts$/, ""), tables)
}

const TABS = {
  Muster: ["attendance-tab", "attendance-workspace", "attendance-report-tab", "attendance-monthly-grid", "attendance-yearly-summary", "attendance-scanner-tab", "attendance-device-settings"],
  Payroll: ["payroll-summary-tab", "worker-profiles-tab", "workers/pay-rule-form", "workers/worker-money-panel"],
  Costs: ["labor-deployment-tab", "other-expenses-tab", "accounts-page", "accounts/labour-cost-summary"],
  Picking: ["picking-log-tab"],
  Processing: ["processing-tab", "pepper-tab"],
  Dispatch: ["dispatch-tab"],
  Sales: ["sales-tab", "other-sales-tab"],
  Inventory: ["inventory-system", "inventory-dialogs", "inventory-system/transaction-history-panel"],
  "Balance Sheet": ["balance-sheet-tab"],
  Season: ["season-dashboard"],
  Rainfall: ["rainfall-tab"],
  AI: ["ai-analysis-tab", "morning-brief-card", "floating-ai-assistant"],
}

const byTable = new Map()
for (const [tab, stems] of Object.entries(TABS)) {
  for (const stem of stems) {
    let src
    try {
      src = readFileSync(`components/${stem}.tsx`, "utf8")
    } catch {
      continue
    }
    for (const m of src.matchAll(/["'`](\/api\/[a-z0-9\-_/[\]$.{}]+)/gi)) {
      const base = m[1].split("?")[0].replace(/\/\$\{.*$/, "")
      for (const [route, tables] of routeTables) {
        if (base !== route && !base.startsWith(route + "/")) continue
        for (const t of tables) {
          if (!byTable.has(t)) byTable.set(t, new Set())
          byTable.get(t).add(tab)
        }
      }
    }
  }
}

const shared = [...byTable.entries()]
  .filter(([t, tabs]) => tabs.size > 1 && !UBIQUITOUS.includes(t))
  .sort((a, b) => b[1].size - a[1].size || a[0].localeCompare(b[0]))

const rows = shared.map(([t, tabs]) => `| \`${t}\` | ${tabs.size} | ${[...tabs].sort().join(", ")} |`)

/**
 * ⚠ THE WHOLE FILE IS WRITTEN HERE, not just the table.
 *
 * The first version printed the table to stdout and the document said "Generated by
 * `node scripts/dev/tab-seams.mjs` (re-run it; do not hand-edit the table)". That instruction was
 * FALSE -- the script wrote nothing -- so the map was pasted in by hand, the paste was truncated
 * at 18 of 24 rows, and the summary line underneath went on claiming 24. Six seams were missing
 * from the one artifact whose entire job is "do not miss a seam", and the count sitting beside
 * them said nothing was missing. Raised by Greptile on PR #21.
 *
 * A generated file that a human has to assemble is a file that drifts on its first update. The
 * prose lives here so the instruction is true.
 */
const doc = `# Where the tabs touch — the seam map

<!-- GENERATED FILE — run \`node scripts/dev/tab-seams.mjs\` to regenerate. Do not hand-edit. -->

Every tab's components are read for \`fetch("/api/…")\` calls, every API route is read for the
tables it queries, and the two are joined. Table names are checked against the live schema, so a
SQL keyword or a CTE alias cannot masquerade as a table.

\`${UBIQUITOUS.join("`, `")}\` are excluded — everything touches them and their presence in a
list says nothing.

## Why this file exists

**Every expensive bug this project has had lived on a seam, not inside a tab.** Not one of them
was a crash; all of them were a screen confidently reporting a number that another screen, reading
the same rows, would have reported differently:

| What happened | Seam | Cost |
|---|---|---|
| Revaluation counted as trade in 3 of 5 readers of the same table | \`transaction_history\` | ₹105.78 cr phantom depletion, ₹64.42 cr phantom purchases |
| Retention never applied to estates that mark attendance but allocate no work | \`attendance_records\` ↔ \`labour_assignments\` | ₹62,020 not withheld, ₹37,600 of it one worker's |
| Net Payable rendered under the heading "Overtime" | payroll header vs body | the figure an estate counts cash from |
| 28 workers accruing absences after leaving the roster | \`attendance_workers\` ↔ \`attendance_records\` | 25 of them on one tenant |
| Same day booked twice, >1.0 day per worker | \`labour_assignments\` | 135 worker-days nobody worked |

A per-tab reviewer sees one side of each of those and finds nothing wrong, because nothing *is*
wrong on one side. That is the argument for the \`seam-auditor\`.

## The map

| Table | Tabs | Which |
|---|---|---|
${rows.join("\n")}

**${shared.length} shared business tables** across ${byTable.size} touched; ${real.size} tables in the schema.

## The seams that carry money

Start here. These are where a disagreement is a rupee figure rather than a cosmetic one:

1. **\`transaction_history\`** — Inventory, Balance Sheet, Season, Costs, *and* \`lib/server/ai-analysis.ts\`.
   Revaluation rows are real money and not trade. Three of these got it wrong once already, and
   \`ai-analysis\` was still wrong on 2026-09-15.
2. **\`labour_assignments\`** — the same day's work priced five ways. Day fractions totalling >1.0
   live here.
3. **\`attendance_records\`** — a day marked present with no allocation still earns a wage in
   Payroll; the Muster can be silent about it.
4. **\`current_inventory\` ↔ \`transaction_history\`** — the ledger replay must reconcile against the
   balance. Filtering rows out of a balance breaks the reconciliation that proves the balance.
5. **\`processing_records\` → \`dispatch_records\` → \`sales_records\`** — kg in, bags out, kg sold.
   Three tabs, one physical quantity, three chances to disagree.
6. **\`booked_revenue\` ↔ \`sales_records\` ↔ \`receivables\`** — revenue recognised, invoiced,
   collected. Balance Sheet and Season both narrate this.

## Reading this map honestly

A tab appearing beside a table means *some route that tab calls mentions that table* — it does not
mean the tab surfaces a number derived from it. Rainfall appears against several tables because its
route calls a shared summary endpoint, not because rainfall has an opinion about sales. **Confirm
the read path before writing a finding**; the map narrows where to look, it is not evidence.
`

writeFileSync("docs/TAB-SEAMS.md", doc)
console.log(`docs/TAB-SEAMS.md written — ${shared.length} shared tables, ${rows.length} rows.`)
if (shared.length !== rows.length) {
  console.error("row count does not match the stated total")
  process.exit(1)
}
